# Generated by Django 4.2.20 on 2025-03-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set Book as Returned'),), 'verbose_name': 'Book Instance'},
        ),
    ]
